// Curated tag lists for the "Interests" / "Languages" pickers — replaces the
// old free-text comma-separated inputs (nobody could tell what to type
// there). Each interest carries its own emoji so the chip grid reads like
// Hinge/Bumble's interest picker rather than a plain word list. Stored on
// the wire as the raw `key` (language-independent); the label shown comes
// from i18n via `interests.<key>` / `languages.<key>`.
export const INTEREST_KEYS = [
  "hiking",
  "camping",
  "travel",
  "photography",
  "movies",
  "music",
  "reading",
  "gaming",
  "cooking",
  "baking",
  "coffee",
  "wine",
  "art",
  "dancing",
  "yoga",
  "fitness",
  "running",
  "cycling",
  "swimming",
  "golf",
  "skiing",
  "sports",
  "pets",
  "fashion",
  "concerts",
  "volunteering",
] as const;

export const INTEREST_EMOJI: Record<(typeof INTEREST_KEYS)[number], string> = {
  hiking: "🥾",
  camping: "🏕️",
  travel: "✈️",
  photography: "📸",
  movies: "🎬",
  music: "🎵",
  reading: "📚",
  gaming: "🎮",
  cooking: "🍳",
  baking: "🍰",
  coffee: "☕",
  wine: "🍷",
  art: "🎨",
  dancing: "💃",
  yoga: "🧘",
  fitness: "💪",
  running: "🏃",
  cycling: "🚴",
  swimming: "🏊",
  golf: "⛳",
  skiing: "⛷️",
  sports: "⚽",
  pets: "🐶",
  fashion: "👗",
  concerts: "🎤",
  volunteering: "🤝",
};

export const LANGUAGE_KEYS = [
  "korean",
  "english",
  "japanese",
  "chinese",
  "spanish",
  "french",
  "german",
  "vietnamese",
  "thai",
  "tagalog",
  "russian",
  "portuguese",
  "italian",
  "arabic",
  "hindi",
] as const;
